Repository Arquisoft/dede_es2a, pull requests merged in 2022-05, with the labels that each got.

#201 Para el despliegue
  docker-compose-deploy.yml
  restapi/modules/cloudinary.ts
  restapi/modules/gestorDB.ts
  restapi/server.ts
  webapp/Dockerfile
Labels: Despliegue🚀

#202 Prueba despliegue
  .github/workflows/asw2122.ts
  docker-compose-deploy.yml
  restapi/.env
  restapi/models/Juguete.ts
  restapi/models/Usuario.ts
  restapi/modules/cloudinary.ts
  restapi/package-lock.json
  restapi/repositories/JuguetesRepository.ts
  restapi/repositories/PedidosRepository.ts
  restapi/repositories/UsuarioRepository.ts
  restapi/routes/juguete.router.ts
  restapi/routes/pedido.router.ts
  restapi/routes/usuario.router.ts
  restapi/server.ts
  restapi/tests/datos/pedidos.json
  restapi/tests/juguete.test.ts
  restapi/tests/pedido.test.ts
  webapp/Dockerfile
  webapp/e2e/features/register-form.feature
  webapp/e2e/features/register-user.feature
  webapp/e2e/jest.config.ts
  webapp/e2e/steps/add-to-cart.steps.ts
  webapp/e2e/steps/pay-process.steps.ts
  webapp/e2e/steps/register-user.steps.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/Cart/Cart.tsx
  webapp/src/CartItem/CartItem.tsx
  webapp/src/Item/Item.tsx
  webapp/src/PayForm/CategoriesBar.tsx
  webapp/src/PayForm/FinalizedOrder.tsx
  webapp/src/PayForm/ProcesoPago.tsx
  webapp/src/PayForm/Review.tsx
  webapp/src/PayForm/Shipping.tsx
  webapp/src/PayForm/categories.css
  webapp/src/componentes/Login/LoginButton.tsx
  webapp/src/componentes/loginSOLID/LoginForm.tsx
  webapp/src/componentes/loginSOLID/LogoutForm.tsx
  webapp/src/paginas/Home.tsx
Labels: Despliegue🚀

#203 Cosas de categorias y demás
  webapp/src/App.tsx
  webapp/src/PayForm/CategoriesBar.tsx
  webapp/src/PayForm/ProcesoPago.tsx
  webapp/src/PayForm/categories.css
Labels: REACT ⚛

#205 Historial pedidos
  restapi/package-lock.json
  restapi/routes/juguete.router.ts
  restapi/routes/pedido.router.ts
  webapp/src/App.tsx
  webapp/src/PayForm/ProcesoPago.tsx
  webapp/src/componentes/Login/LoginButton.tsx
  webapp/src/componentes/Navbar/Menitems.tsx
  webapp/src/componentes/Pedidos/PedidoItem.tsx
  webapp/src/componentes/Pedidos/historial.tsx
  webapp/src/componentes/Pedidos/pedidos.css
  webapp/src/shared/sharedPedido.ts
Labels: REACT ⚛, diseño ✏

#207 Despliegue
  .github/workflows/pruebaDeploy.yml
  restapi/Dockerfile
  restapi/server.ts
  webapp/server.ts
Labels: Despliegue🚀

#208 Despliegue
  .github/workflows/pruebaDeploy.yml
  restapi/Dockerfile
  restapi/package-lock.json
  restapi/routes/juguete.router.ts
  restapi/routes/pedido.router.ts
  restapi/server.ts
  webapp/server.ts
  webapp/src/App.tsx
  webapp/src/Item/Item.tsx
  webapp/src/PayForm/CategoriesBar.tsx
  webapp/src/PayForm/ProcesoPago.tsx
  webapp/src/PayForm/categories.css
  webapp/src/componentes/Login/LoginButton.tsx
  webapp/src/componentes/Navbar/Menitems.tsx
  webapp/src/componentes/Navbar/Navbar.tsx
  webapp/src/componentes/Pedidos/PedidoItem.tsx
  webapp/src/componentes/Pedidos/historial.tsx
  webapp/src/componentes/Pedidos/pedidos.css
  webapp/src/paginas/Home.tsx
  webapp/src/shared/sharedPedido.ts
  webapp/src/tests/dynamicrouting.test.tsx
Labels: Despliegue🚀

#209 Ultimo retoque para el despliegue
  webapp/server.ts
Labels: Despliegue🚀

#210 Ultimo retoque para despliegue
  webapp/server.ts
Labels: Despliegue🚀

#214 Puntos de la documentación actualizados
  docs/01_introduction_and_goals.adoc
  docs/02_architecture_constraints.adoc
  docs/04_solution_strategy.adoc
  docs/05_building_block_view.adoc
  docs/06_runtime_view.adoc
  docs/07_deployment_view.adoc
  docs/08_concepts.adoc
  docs/09_design_decisions.adoc
  docs/10_quality_scenarios.adoc
  docs/11_technical_risks.adoc
  docs/12_glossary.adoc
  docs/images/JugueteBloqueConstruccion.png
  docs/images/PedidoBloqueConstruccion.png
  docs/images/UsuarioBloqueConstruccion.png
  restapi/routes/juguete.router.ts
Labels: documentación 📖

#220 Validación formularios
  restapi/routes/juguete.router.ts
  webapp/src/PayForm/ProcesoPago.tsx
  webapp/src/PayForm/Shipping.tsx
  webapp/src/componentes/editarProducto/editarProducto.tsx
  webapp/src/componentes/nuevoProducto/nuevoProducto.tsx
Labels: bug 🐞, REACT ⚛, diseño ✏

#221 Tests unitarios bastante avanzados y aspectos generales de la app
  webapp/src/App.styles.ts
  webapp/src/App.test.tsx
  webapp/src/App.tsx
  webapp/src/Item/Item.tsx
  webapp/src/PayForm/Delivery.tsx
  webapp/src/PayForm/FinalizedOrder.tsx
  webapp/src/PayForm/ProcesoPago.tsx
  webapp/src/PayForm/Review.tsx
  webapp/src/PayForm/Shipping.tsx
  webapp/src/PayForm/Summary.tsx
  webapp/src/componentes/Login/LoginButton.tsx
  webapp/src/componentes/Navbar/Navbar.tsx
  webapp/src/componentes/Pedidos/historial.tsx
  webapp/src/componentes/loginSOLID/LoginForm.tsx
  webapp/src/componentes/loginSOLID/LogoutForm.tsx
  webapp/src/componentes/loginSOLID/Profile.tsx
  webapp/src/index.tsx
  webapp/src/paginas/Home.tsx
  webapp/src/tests/dynamicrouting.test.tsx
Labels: REACT ⚛, testing ⏳

#223 Avances test e2e, merge necesario para desarrollo de la app
  docs/06_runtime_view.adoc
  webapp/e2e/features/orders-history.feature
  webapp/e2e/steps/add-to-cart.steps.ts
  webapp/e2e/steps/orders-history.steps.ts
  webapp/e2e/steps/pay-process.steps.ts
  webapp/e2e/steps/register-form.steps.ts
  webapp/src/App.styles.ts
  webapp/src/App.tsx
  webapp/src/Cart/Cart.tsx
  webapp/src/Item/Item.tsx
  webapp/src/PayForm/CategoriesBar.tsx
  webapp/src/PayForm/Delivery.tsx
  webapp/src/PayForm/FinalizedOrder.tsx
  webapp/src/PayForm/Review.tsx
  webapp/src/PayForm/Shipping.tsx
  webapp/src/componentes/Navbar/Navbar.css
  webapp/src/paginas/Home.tsx
  webapp/src/paginas/Pag.css
  webapp/src/paginas/fondonostalgia.jpg
  webapp/src/tests/dynamicrouting.test.tsx
Labels: REACT ⚛, testing ⏳

#230 Tests e2e, arreglos estéticos, y de funcionamiento general
  webapp/e2e/jest.config.ts
  webapp/e2e/steps/add-to-cart.steps.ts
  webapp/e2e/steps/orders-history.steps.ts
  webapp/e2e/steps/pay-process.steps.ts
  webapp/package-lock.json
  webapp/package.json
Labels: REACT ⚛, testing ⏳

#231 musicales y arreglo categorias en addJuguete
  restapi/routes/juguete.router.ts
  webapp/src/App.tsx
  webapp/src/PayForm/CategoriesBar.tsx
  webapp/src/componentes/Pedidos/historial.tsx
  webapp/src/componentes/Pedidos/pedidos.css
  webapp/src/componentes/editarProducto/editarProducto.tsx
  webapp/src/componentes/nuevoProducto/nuevoProducto.tsx
  webapp/src/paginas/Home.tsx
  webapp/src/tests/dynamicrouting.test.tsx
Labels: bug 🐞, REACT ⚛, diseño ✏

#232 Documentación casi completa y arreglos en los tests de restapi
  docs/06_runtime_view.adoc
  docs/images/modeloDominio.png
  restapi/routes/usuario.router.ts
  restapi/tests/datos/usuarios.json
  restapi/tests/pedido.test.ts
  restapi/tests/usuario.test.ts
Labels: documentación 📖, NODE.js 🍃

#233 Despliegue
  .github/workflows/pruebaDeploy.ts
  .github/workflows/pruebaSinDocker.yml
  restapi/.gitignore
  restapi/Dockerfile
  restapi/modules/cloudinary.ts
  restapi/modules/gestorDB.ts
  restapi/server.ts
  webapp/Dockerfile
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/Item/Item.tsx
  webapp/src/PayForm/ProcesoPago.tsx
  webapp/src/api/api.ts
  webapp/src/componentes/Pedidos/historial.tsx
  webapp/src/componentes/editarProducto/editarProducto.tsx
  webapp/src/componentes/nuevoProducto/nuevoProducto.tsx
Labels: despliegue🚀

#235 cambio navbar.css
  webapp/src/componentes/Login/LogoutButton.tsx
  webapp/src/componentes/Navbar/Navbar.css
  webapp/src/tests/dynamicrouting.test.tsx
Labels: bug 🐞, diseño ✏

#236 Retoques documentación y estética de la aplicación
  docs/06_runtime_view.adoc
  webapp/src/Cart/Cart.tsx
Labels: documentación 📖, REACT ⚛

#240 Ultima union
  .github/workflows/asw2122.ts
  .github/workflows/asw2122.yml
  .github/workflows/pruebaDeploy.ts
  README.md
  README_es.md
  restapi/modules/cloudinary.ts
  restapi/modules/gestorDB.ts
  restapi/routes/juguete.router.ts
  restapi/routes/pedido.router.ts
  restapi/routes/usuario.router.ts
  restapi/tests/juguete.test.ts
  webapp/e2e/steps/orders-history.steps.ts
  webapp/e2e/steps/pay-process.steps.ts
  webapp/e2e/steps/register-user.steps.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/Cart/Cart.tsx
  webapp/src/CartItem/CartItem.tsx
  webapp/src/Item/Item.tsx
  webapp/src/PayForm/Delivery.tsx
  webapp/src/PayForm/FinalizedOrder.tsx
  webapp/src/PayForm/ProcesoPago.tsx
  webapp/src/PayForm/Review.tsx
  webapp/src/PayForm/SummaryItem.tsx
  webapp/src/componentes/Login/LoginButtonCart.tsx
  webapp/src/componentes/Pedidos/PedidoItem.tsx
  webapp/src/componentes/Pedidos/historial.tsx
  webapp/src/componentes/editarProducto/editarProducto.tsx
  webapp/src/componentes/loginSOLID/LoginForm.tsx
  webapp/src/componentes/loginSOLID/LogoutForm.tsx
  webapp/src/componentes/nuevoProducto/nuevoProducto.tsx
  webapp/src/paginas/Home.tsx
  webapp/src/tests/dynamicrouting.test.tsx
Labels: bug 🐞

#241 Documentación finalizada
  docs/11_technical_risks.adoc
Labels: documentación 📖

#249 Arreglo url
  webapp/src/PayForm/ProcesoPago.tsx
Labels: bug 🐞

#250 Arreglo url
  webapp/src/componentes/editarProducto/editarProducto.tsx
Labels: bug 🐞
