Repository Arquisoft/dede_es2a, pull requests merged in 2022-03, with the labels that each got.

#51 Tercer intento login jorge
  package-lock.json
  package.json
  webapp/package-lock.json
  webapp/package.json
  webapp/public/index.html
  webapp/src/App.css
  webapp/src/App.styles.ts
  webapp/src/App.tsx
  webapp/src/Cart/Cart.styles.ts
  webapp/src/Cart/Cart.tsx
  webapp/src/CartItem/CartItem.styles.ts
  webapp/src/CartItem/CartItem.tsx
  webapp/src/Item/Item.styles.ts
  webapp/src/Item/Item.tsx
  webapp/src/componentes/Button.css
  webapp/src/componentes/Button.js
  webapp/src/componentes/Login/LoginButton.tsx
  webapp/src/componentes/Login/LogoutButton.tsx
  webapp/src/componentes/Login/Profile.tsx
  webapp/src/componentes/Navbar/Menitems.tsx
  webapp/src/componentes/Navbar/Navbar.css
  webapp/src/componentes/Navbar/Navbar.tsx
  webapp/src/index.css
  webapp/src/index.tsx
Labels: REACT, pull-request

#55 Backend
  .gitignore
  package-lock.json
  package.json
  restapi/models/Juguete.ts
  restapi/modules/gestorDB.ts
  restapi/package-lock.json
  restapi/package.json
  restapi/routes/juguete.router.ts
  restapi/server.ts
  webapp/package-lock.json
  webapp/src/App.tsx
  webapp/src/Cart/Cart.tsx
  webapp/src/CartItem/CartItem.tsx
  webapp/src/Item/Item.tsx
  webapp/src/images/pika.png
  webapp/src/shared/sharedJuguete.ts
Labels: BD, NODE.js

#57 Prototipo
  restapi/.env
  webapp/src/App.tsx
  webapp/src/Item/Item.tsx
Labels: pull-request

#66 Prototipo
  .gitignore
  docs/04_solution_strategy.adoc
  docs/06_runtime_view.adoc
  docs/10_quality_scenarios.adoc
  docs/11_technical_risks.adoc
  package-lock.json
  package.json
  restapi/.env
  restapi/models/Juguete.ts
  restapi/modules/gestorDB.ts
  restapi/package-lock.json
  restapi/package.json
  restapi/routes/juguete.router.ts
  restapi/server.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/public/index.html
  webapp/src/App.css
  webapp/src/App.styles.ts
  webapp/src/App.tsx
  webapp/src/Cart/Cart.styles.ts
  webapp/src/Cart/Cart.tsx
  webapp/src/CartItem/CartItem.styles.ts
  webapp/src/CartItem/CartItem.tsx
  webapp/src/Item/Item.styles.ts
  webapp/src/Item/Item.tsx
  webapp/src/componentes/Button.css
  webapp/src/componentes/Button.js
  webapp/src/componentes/Footer/Footer.css
  webapp/src/componentes/Footer/Footer.tsx
  webapp/src/componentes/Login/LoginButton.tsx
  webapp/src/componentes/Login/LogoutButton.tsx
  webapp/src/componentes/Login/Profile.tsx
  webapp/src/componentes/Navbar/Menitems.tsx
  webapp/src/componentes/Navbar/Navbar.css
  webapp/src/componentes/Navbar/Navbar.tsx
  webapp/src/images/pika.png
  webapp/src/index.css
  webapp/src/index.tsx
  webapp/src/shared/sharedJuguete.ts
Labels: trabajo realizado, BD, REACT, NODE.js

#81 Enlace documentación arreglado
  docs/README_es.md
Labels: bug 🐞, documentación 📖

#84 Testing
  restapi/modules/gestorDB.ts
  restapi/routes/juguete.router.ts
  restapi/server.ts
  restapi/tests/api.test.ts
  restapi/tests/jest.config.ts
  restapi/tests/pruebaTest.ts
Labels: testing ⏳
