Repository Arquisoft/dede_es2a, pull requests merged in 2022-04, with the labels that each got.

#99 Primera versión pruebas backend
  restapi/routes/juguete.router.ts
  restapi/tests/api.test.ts
Labels: NODE.js 🍃

#100 Arreglo de Backend, arreglo de pruebas y comienzo de pedido
  restapi/models/Juguete.ts
  restapi/models/Pedido.ts
  restapi/modules/gestorDB.ts
  restapi/routes/juguete.router.ts
  restapi/routes/pedido.router.ts
  restapi/server.ts
  restapi/tests/api.test.ts
  restapi/tests/mock.ts
  restapi/tests/pruebaTest.ts
  webapp/src/shared/shareddtypes.ts
Labels: bug 🐞, BD 🥒, NODE.js 🍃, testing ⏳

#105 Pruebas backend completa
  restapi/models/Pedido.ts
  restapi/models/Usuario.ts
  restapi/routes/juguete.router.ts
  restapi/tests/api.test.ts
  webapp/src/App.tsx
Labels: BD 🥒, NODE.js 🍃

#93 Arreglos de documentación
  docs/05_building_block_view.adoc
  docs/06_runtime_view.adoc
  docs/12_glossary.adoc
  webapp/src/componentes/Login/LoginButton.tsx
  webapp/src/componentes/Login/ProfileImg.tsx
  webapp/src/componentes/Login/ProfileName.tsx
  webapp/src/componentes/Navbar/Navbar.css
  webapp/src/componentes/Navbar/Navbar.tsx
Labels: documentación 📖, investigación 🔎

#107 Documentacion
  docs/02_architecture_constraints.adoc
  restapi/models/Pedido.ts
Labels: documentación 📖

#109 Arreglado enlace a nuestra documentación en README_es
  docs/README_es.md
Labels: bug 🐞, documentación 📖

#114 Segundo prototipo
  docs/02_architecture_constraints.adoc
  docs/05_building_block_view.adoc
  docs/06_runtime_view.adoc
  docs/12_glossary.adoc
  docs/README_es.md
  package-lock.json
  package.json
  restapi/models/Juguete.ts
  restapi/models/Pedido.ts
  restapi/models/Usuario.ts
  restapi/modules/gestorDB.ts
  restapi/routes/juguete.router.ts
  restapi/routes/pedido.router.ts
  restapi/server.ts
  restapi/tests/api.test.ts
  restapi/tests/mock.ts
  restapi/tests/pruebaTest.ts
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/Cart/Cart.styles.ts
  webapp/src/Cart/Cart.tsx
  webapp/src/CartItem/CartItem.tsx
  webapp/src/PayForm/PayForm.tsx
  webapp/src/componentes/Login/LoginButton.tsx
  webapp/src/componentes/Login/ProfileImg.tsx
  webapp/src/componentes/Login/ProfileName.tsx
  webapp/src/componentes/Navbar/Menitems.tsx
  webapp/src/componentes/Navbar/Navbar.css
  webapp/src/componentes/Navbar/Navbar.tsx
  webapp/src/components/EmailForm.test.tsx
  webapp/src/components/EmailForm.tsx
  webapp/src/components/UserList.test.tsx
  webapp/src/components/UserList.tsx
  webapp/src/components/Welcome.test.tsx
  webapp/src/components/Welcome.tsx
  webapp/src/paginas/ContactUs.tsx
  webapp/src/paginas/Home.tsx
  webapp/src/paginas/Pag.css
  webapp/src/shared/sharedUser.ts
  webapp/src/shared/shareddtypes.ts
  webapp/src/tests/Login.test.tsx
  webapp/src/tests/ShoppingCart.test.tsx
  webapp/src/tests/dynamicrouting.test.tsx
Labels: bug 🐞, documentación 📖, investigación 🔎, BD 🥒, REACT ⚛, NODE.js 🍃, pull-request 👾, testing ⏳

#136 Introducción a los PODs de SOLID
  restapi/tests/jest.config.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/componentes/loginSOLID/LoginForm.tsx
  webapp/src/componentes/loginSOLID/LogoutForm.tsx
  webapp/src/componentes/loginSOLID/Profile.tsx
  webapp/src/index.tsx
Labels: REACT ⚛, pull-request 👾

#138 BackEnd, Testing y Docker
  docs/06_runtime_view.adoc
  restapi/models/Juguete.ts
  restapi/models/Pedido.ts
  restapi/models/Usuario.ts
  restapi/repositories/JuguetesRepository.ts
  restapi/repositories/PedidosRepository.ts
  restapi/routes/juguete.router.ts
  restapi/routes/pedido.router.ts
  restapi/server.ts
  restapi/tests/api.test.ts
  webapp/Dockerfile
Labels: BD 🥒, NODE.js 🍃, testing ⏳

#148 Actualización completa punto 3
  docs/03_system_scope_and_context.adoc
  docs/06_runtime_view.adoc
  docs/images/03_system_scope_and_context_BusinessDiagram.png
  docs/images/03_system_scope_and_context_TechnicalDiagram.png
Labels: documentación 📖

#157 BackEnd metodos Pedido
  restapi/models/Pedido.ts
  restapi/modules/gestorDB.ts
  restapi/repositories/JuguetesRepository.ts
  restapi/repositories/PedidosRepository.ts
  restapi/repositories/UsuarioRepository.ts
  restapi/routes/juguete.router.ts
  restapi/routes/pedido.router.ts
  restapi/tests/api.test.ts
Labels: BD 🥒, NODE.js 🍃

#158 Gastos de envío v1
  restapi/package-lock.json
  restapi/package.json
  restapi/repositories/PedidosRepository.ts
  restapi/routes/pedido.router.ts
Labels: NODE.js 🍃

#160 Usuario y Pedido
  restapi/models/Pedido.ts
  restapi/models/Usuario.ts
  restapi/repositories/PedidosRepository.ts
  restapi/routes/pedido.router.ts
  restapi/routes/usuario.router.ts
  restapi/server.ts
Labels: bug 🐞, BD 🥒, NODE.js 🍃

#164 Integración gastos envío en frontend
  restapi/repositories/PedidosRepository.ts
  restapi/routes/pedido.router.ts
  webapp/src/PayForm/Delivery.tsx
  webapp/src/PayForm/ProcesoPago.tsx
Labels: REACT ⚛, NODE.js 🍃

#167 Cloudinary
  restapi/package-lock.json
  restapi/package.json
  restapi/routes/juguete.router.ts
  restapi/server.ts
Labels: BD 🥒, NODE.js 🍃

#169 Despliegue de la app y workflow
  .github/workflows/asw2122.yml
  docker-compose-deploy.yml
  restapi/server.ts
  webapp/Dockerfile
Labels: investigación 🔎, NODE.js 🍃, Despliegue🚀

#171 Adaptado entrega a proceso pago
  webapp/src/PayForm/Delivery.tsx
  webapp/src/PayForm/ProcesoPago.tsx
  webapp/src/PayForm/Review.tsx
  webapp/src/PayForm/Shipping.tsx
  webapp/src/PayForm/SummaryItem.tsx
Labels: REACT ⚛

#174 Testing Backend
  restapi/models/Juguete.ts
  restapi/models/Usuario.ts
  restapi/modules/gestorDB.ts
  restapi/repositories/JuguetesRepository.ts
  restapi/repositories/PedidosRepository.ts
  restapi/repositories/UsuarioRepository.ts
  restapi/routes/juguete.router.ts
  restapi/routes/pedido.router.ts
  restapi/routes/usuario.router.ts
  restapi/server.ts
  restapi/tests/datos/juguetes.json
  restapi/tests/datos/pedidos.json
  restapi/tests/datos/usuarios.json
  restapi/tests/juguete.test.ts
  restapi/tests/juguete.ts
  restapi/tests/mock.ts
  restapi/tests/pedido.test.ts
  restapi/tests/pruebaTest.ts
  restapi/tests/usuario.test.ts
Labels: BD 🥒, NODE.js 🍃

#179 Testing
  .github/workflows/asw2122.yml
  restapi/modules/cloudinary.ts
  restapi/repositories/PedidosRepository.ts
  restapi/routes/juguete.router.ts
  restapi/routes/pedido.router.ts
  restapi/routes/usuario.router.ts
  restapi/server.ts
  restapi/tests/datos/juguetes.json
  restapi/tests/juguete.test.ts
  restapi/tests/pedido.test.ts
  restapi/tests/usuario.test.ts
Labels: BD 🥒, testing ⏳

#180 Intento tests e2e
  webapp/e2e/features/add-to-cart.feature
  webapp/e2e/features/pay-process.feature
  webapp/e2e/steps/add-to-cart.steps.ts
  webapp/e2e/steps/pay-process.steps.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/tests/ShoppingCart.test.tsx
Labels: REACT ⚛

#182 Documentación actualizada pero sin estar completa
  docs/05_building_block_view.adoc
  docs/images/bloqueConstruccion.png
Labels: documentación 📖

#184 Testing gastos de envío
  restapi/routes/pedido.router.ts
  restapi/tests/pedido.test.ts
Labels: NODE.js 🍃, testing ⏳

#186 Union a master para intento despliegue
  .github/workflows/asw2122.yml
  docs/01_introduction_and_goals.adoc
  docs/04_solution_strategy.adoc
  docs/05_building_block_view.adoc
  docs/07_deployment_view.adoc
  docs/08_concepts.adoc
  docs/09_design_decisions.adoc
  docs/images/bloqueConstruccion.png
  docs/images/infraestructura.png
  docs/images/modeloDominio.png
  package.json
  restapi/modules/cloudinary.ts
  restapi/package.json
  restapi/repositories/PedidosRepository.ts
  restapi/routes/juguete.router.ts
  restapi/routes/pedido.router.ts
  restapi/routes/usuario.router.ts
  restapi/server.ts
  restapi/tests/datos/juguetes.json
  restapi/tests/juguete.test.ts
  restapi/tests/pedido.test.ts
  restapi/tests/usuario.test.ts
  webapp/e2e/features/add-to-cart.feature
  webapp/e2e/features/pay-process.feature
  webapp/e2e/steps/add-to-cart.steps.ts
  webapp/e2e/steps/pay-process.steps.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/tests/ShoppingCart.test.tsx
Labels: REACT ⚛, Despliegue🚀

#187 Variables de entorno
  restapi/.env
  restapi/models/Juguete.ts
  restapi/modules/cloudinary.ts
  restapi/modules/gestorDB.ts
  restapi/repositories/PedidosRepository.ts
  restapi/routes/juguete.router.ts
  restapi/routes/pedido.router.ts
  restapi/routes/usuario.router.ts
  restapi/server.ts
  restapi/tests/datos/pedidos.json
  restapi/tests/juguete.test.ts
  restapi/tests/pedido.test.ts
Labels: NODE.js 🍃

#190 Tests e2e y algunos arreglos de POD
  webapp/e2e/features/register-form.feature
  webapp/e2e/features/register-user.feature
  webapp/e2e/jest.config.ts
  webapp/e2e/steps/add-to-cart.steps.ts
  webapp/e2e/steps/pay-process.steps.ts
  webapp/e2e/steps/register-form.steps.ts
  webapp/e2e/steps/register-user.steps.ts
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/Cart/Cart.tsx
  webapp/src/CartItem/CartItem.tsx
  webapp/src/PayForm/Shipping.tsx
  webapp/src/componentes/Login/LoginButton.tsx
  webapp/src/componentes/loginSOLID/LoginForm.tsx
Labels: REACT ⚛, testing ⏳

#192 Eliminacion de repositorios y corregir test
  .github/workflows/asw2122.yml
  restapi/package-lock.json
  restapi/repositories/JuguetesRepository.ts
  restapi/repositories/PedidosRepository.ts
  restapi/repositories/UsuarioRepository.ts
  restapi/routes/juguete.router.ts
  restapi/routes/pedido.router.ts
  restapi/routes/usuario.router.ts
  restapi/tests/juguete.test.ts
Labels: BD 🥒, NODE.js 🍃

#194 Peticion que filtra juguetes por categoria
  restapi/routes/juguete.router.ts
Labels: NODE.js 🍃

#195 Inicio de creacion Categories Bar
  restapi/routes/pedido.router.ts
  webapp/src/App.tsx
  webapp/src/Item/Item.tsx
  webapp/src/PayForm/CategoriesBar.tsx
  webapp/src/PayForm/ProcesoPago.tsx
  webapp/src/PayForm/Review.tsx
  webapp/src/PayForm/Shipping.tsx
  webapp/src/componentes/Login/LoginButton.tsx
  webapp/src/componentes/loginSOLID/LoginForm.tsx
  webapp/src/componentes/loginSOLID/LogoutForm.tsx
Labels: REACT ⚛

#196 Mas avances barra categorias
  webapp/src/App.tsx
  webapp/src/PayForm/CategoriesBar.tsx
  webapp/src/PayForm/categories.css
Labels: REACT ⚛

#199 Se añaden usuarios tras registro
  restapi/models/Usuario.ts
  restapi/routes/juguete.router.ts
  restapi/routes/usuario.router.ts
  webapp/src/componentes/Login/LoginButton.tsx
  webapp/src/paginas/Home.tsx
Labels: BD 🥒, REACT ⚛, NODE.js 🍃

#200 Juntado asociar pedido a usuario con usuario base de datos
  webapp/src/PayForm/ProcesoPago.tsx
Labels: REACT ⚛, NODE.js 🍃
